name: Deploy LLM Service to GCP Run

on:
    push:
        branches:
            - main
        paths:
            - 'server/llm_service/**'
            - '.github/workflows/deploy-backend-llm.yml'

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - id: 'auth'
              uses: 'google-github-actions/auth@v2'
              with:
                  credentials_json: '${{ secrets.GCP_SA_KEY }}'

            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v2'

            - name: 'Build and Push Docker image'
              run: |-
                  gcloud auth configure-docker asia-northeast3-docker.pkg.dev
                  docker build -t asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hamkkekids/backend-llm:latest -f server/Dockerfile.llm ./server
                  docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hamkkekids/backend-llm:latest

            - name: 'Deploy to Cloud Run'
              run: |-
                  gcloud run deploy backend-llm \
                    --image asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hamkkekids/backend-llm:latest \
                    --region asia-northeast3 \
                    --platform managed \
                    --allow-unauthenticated \
                    --set-env-vars="OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
