name: Deploy Integrated Service to GCP Run

on:
    push:
        branches:
            - main
        paths:
            - 'server/**'
            - '.github/workflows/deploy-integrated-service.yml'

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - id: 'auth'
              uses: 'google-github-actions/auth@v2'
              with:
                  credentials_json: '${{ secrets.GCP_SA_KEY }}'

            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v2'

            - name: 'Build and Push Docker image'
              run: |-
                  gcloud auth configure-docker asia-northeast3-docker.pkg.dev
                  docker build -t asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hamkkekids/integrated-service:latest -f server/Dockerfile ./server
                  docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hamkkekids/integrated-service:latest

            - name: 'Deploy to Cloud Run'
              run: |-
                  gcloud run deploy hackathon-integrated-service \
                    --image asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hamkkekids/integrated-service:latest \
                    --region asia-northeast3 \
                    --platform managed \
                    --allow-unauthenticated \
                    --port 8002 \
                    --memory 2Gi \
                    --cpu 1 \
                    --timeout 300 \
                    --concurrency 100 \
                    --set-env-vars="SECRET_KEY=${{ secrets.SECRET_KEY }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"